default: &default
  pool: 5
  timeout: 5000
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  username: postgres

development:
  <<: *default
  database: mental_development

test:
  <<: *default
  database: mental_test

production:
  <<: *default
  database: mental_production

